//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.08 at 11:47:04 AM BST 
//

package com.bridge.jaxb;

public class Activity {

	protected String gateNumber;
	protected int uid;
	protected String direction;
	protected String vehicleType;
	protected String vrn;
	protected String crossingDateAndTime;

	public String getGateNumber() {
		return gateNumber;
	}
	public void setGateNumber(String value) {
		this.gateNumber = value;
	}
	public int getUid() {
		return uid;
	}
	public void setUid(int uid) {
		this.uid = uid;
	}
	public String getDirection() {
		return direction;
	}
	public void setDirection(String value) {
		this.direction = value;
	}
	public String getVehicleType() {
		return vehicleType;
	}
	public void setVehicleType(String value) {
		this.vehicleType = value;
	}
	public String getVrn() {
		return vrn;
	}
	public void setVrn(String value) {
		this.vrn = value;
	}
	public String getCrossingDateAndTime() {
		return crossingDateAndTime;
	}
	public void setCrossingDateAndTime(String value) {
		this.crossingDateAndTime = value;
	}

}
